/*amd /page/P00201.xml 4392 44f963d0298cf4141df4653e1132629549d2c34642782e2bf2e5629b2d0b5dad */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',A:{},E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',id:'dlt_page_history',repeatNode:'map',saveRemovedData:'true',style:''},E:[{T:1,N:'w2:columnInfo',E:[{T:1,N:'w2:column',A:{dataType:'text',id:'updated_date',name:'업데이트 날짜'}},{T:1,N:'w2:column',A:{dataType:'text',id:'version',name:'버전'}},{T:1,N:'w2:column',A:{dataType:'text',id:'description',name:'설명'}},{T:1,N:'w2:column',A:{dataType:'text',id:'author',name:'작성인'}}]},{T:1,N:'w2:data',A:{use:'true'},E:[{T:1,N:'w2:row',E:[{T:1,N:'updated_date',E:[{T:4,cdata:'20230130'}]},{T:1,N:'version',E:[{T:4,cdata:'01'}]},{T:1,N:'description',E:[{T:4,cdata:'최초작성'}]},{T:1,N:'author',E:[{T:4,cdata:'InswaveSystems'}]}]}]}]}]},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){
scwin.onpageload = function () {
    //InputCalendar에 지정할 시스템 날짜를 yyyyMMdd 형태로 저장합니다.
    let sysDate = $p.getCurrentServerDate("yyyyMMdd");

    //InputCalendar 'ica_exam_1'에 시스템 날짜를 지정합니다.
    ica_exam_1.setValue(sysDate);

    //InputCalendar 'ica_exam_2'에 시스템 날짜를 지정합니다.
    ica_exam_2.setValue(sysDate);
};

}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload'},E:[{T:1,N:'xf:group',A:{class:'sub_contents',id:'',style:''},E:[{T:1,N:'xf:group',A:{class:'ws_example_grp_desc',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{escape:'false',id:'',label:'달력 아이콘 클릭, 특정 일(Day)을 선택한 후, 달력 상단의 화살표를 사용하여 월이나 연도를 이동해도 현재 선택한 일을 유지할 수 있습니다.<br/>이 기능은 아래의 속성으로 사용할 수 있습니다.<br/>- dayMoveFixed : 날짜(day) 유지 유무',style:'margin-bottom: 10px;'}}]},{T:1,N:'xf:group',A:{class:'example_div_tb_style_wrap',id:''},E:[{T:1,N:'xf:group',A:{class:'example_div_tr_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'example_div_th_style',escape:'false',id:'',label:'(기본 설정) dayMoveFixed - false',style:''}},{T:1,N:'xf:group',A:{class:'example_div_td_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'ws5_example_txt_normal',escape:'false',id:'',label:'달력 아이콘 클릭 시 표시되는 달력의 좌우 아이콘 \'<\' 을 클릭하여 월을 이동합니다.<br/>달력의 월이 바뀌었고 해당 월의 1일로 날짜가 이동한 것을 확인합니다.',style:''}},{T:1,N:'w2:textbox',A:{class:'txt_info_important',escape:'false',id:'',label:'※ 단 속성과 관계 없이 셀렉트박스로 년(year), 월(month) 수정 시 선택해 둔 일(day)은 유지됩니다.',style:''}},{T:1,N:'w2:inputCalendar',A:{calendarValueType:'yearMonthDate',focusOnDateSelect:'false',id:'ica_exam_1',rightAlign:'false',style:'width:100px;min-height: 24px;',renderDiv:'true',class:'mr_def'}}]}]},{T:1,N:'xf:group',A:{class:'example_div_tr_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'example_div_th_style',escape:'false',id:'',label:'dayMoveFixed - true 적용',style:''}},{T:1,N:'xf:group',A:{class:'example_div_td_style',id:'',style:''},E:[{T:1,N:'w2:textbox',A:{class:'ws5_example_txt_normal',escape:'false',id:'',label:'달력 아이콘 클릭 시 표시되는 달력의 좌우 아이콘 \'<<\' 을 클릭하여 연도를 이동합니다.<br/>달력의 연도가 바뀌고 좌우 아이콘을 클릭하기 전 날짜가 달력에 표시된 것을 확인합니다.',style:''}},{T:1,N:'w2:textbox',A:{class:'txt_info_important',escape:'false',id:'',label:'※ 단 속성과 관계 없이 셀렉트박스로 년(year), 월(month) 수정 시 선택해 둔 일(day)은 유지됩니다.',style:''}},{T:1,N:'w2:inputCalendar',A:{calendarValueType:'yearMonthDate',focusOnDateSelect:'false',id:'ica_exam_2',rightAlign:'false',style:'width:100px;min-height: 24px;',renderDiv:'true',class:'mr_def',dayMoveFixed:'true'}}]}]}]}]}]}]}]})